src/views/ProfileView.py
from flask import jsonify, request, make_response, Blueprint, flash, redirect, render_template, url_for, render_template_string
from flask_jwt_extended.utils import decode_token
from ..models.UserModel import User
from ..models.BlogpostModel import Blogpost
from ..models.EditorialModel import Editorial
from ..models import db
from sqlalchemy import desc
import os
import uuid

from datetime import datetime, timedelta, timezone
from urllib.parse import urlencode
from .forms import RegistrationForm, LoginForm, ProfileEditForm
from . import jwt
from flask_jwt_extended import create_access_token, jwt_required, set_access_cookies, unset_jwt_cookies, get_jwt, get_jwt_identity
from werkzeug.security import generate_password_hash, check_password_hash
from .danger import superadmin_required, staff_required, generate_jwt_access_token

profile_api = Blueprint('profile_api', __name__)

@profile_api.after_request
def refresh_expiring_jwts(response):
    try:
        exp_timestamp = get_jwt()["exp"]
        now = datetime.now(timezone.utc)
        target_timestamp = datetime.timestamp(now + timedelta(minutes=30))
        if target_timestamp > exp_timestamp:
            access_token = create_access_token(identity=get_jwt_identity())
            set_access_cookies(response, access_token)
        return response
    except (RuntimeError, KeyError):
        return response

@profile_api.context_processor
def handle_context():
    return dict(req_args = request.args, int = int, len = len, datetime=datetime, str = str)

@profile_api.route("/upload")
def upload():
    return render_template('upload_posts.html', title='Upload')

src/views/UserView.py
from flask import jsonify, request, make_response, Blueprint, flash, redirect, render_template, url_for, render_template_string
from flask_jwt_extended.utils import decode_token
from ..models.UserModel import User
from ..models.BlogpostModel import Blogpost
from ..models.EditorialModel import Editorial
from ..models import db
from sqlalchemy import desc
import os
import uuid

from datetime import datetime, timedelta, timezone
from urllib.parse import urlencode
from .forms import RegistrationForm, LoginForm, ProfileEditForm
from . import jwt
from flask_jwt_extended import create_access_token, jwt_required, set_access_cookies, unset_jwt_cookies, get_jwt, get_jwt_identity
from werkzeug.security import generate_password_hash, check_password_hash
from .danger import superadmin_required, staff_required, generate_jwt_access_token

user_api = Blueprint('user_api', __name__)

@user_api.after_request
def refresh_expiring_jwts(response):
    try:
        exp_timestamp = get_jwt()["exp"]
        now = datetime.now(timezone.utc)
        target_timestamp = datetime.timestamp(now + timedelta(minutes=30))
        if target_timestamp > exp_timestamp:
            access_token = create_access_token(identity=get_jwt_identity())
            set_access_cookies(response, access_token)
        return response
    except (RuntimeError, KeyError):
        return response

@user_api.context_processor
def handle_context():
    return dict(req_args = request.args, int = int, len = len, datetime=datetime, str = str)

@user_api.route("/")
@user_api.route("/index")
def index():
    featured_editorials = Editorial.query.order_by(desc('date_modified')).limit(4)
    recent_blogs = Blogpost.query.order_by(desc('date_modified')).limit(6)
    return render_template('index.html', recent_blogs = recent_blogs, featured_editorials = featured_editorials)


@user_api.route("/about")
def about():
    return render_template('about.html', title='About')


@user_api.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')

        user = User(
            public_id = str(uuid.uuid4()),
            name = form.name.data,
            email = form.email.data, 
            password = hashed_password,
            role='user+staff+superadmin'
            )

        db.session.add(user)
        db.session.commit()

        flash(f'Your account has been created!', 'success')
        return redirect(url_for('user_api.index'))
    return render_template('register.html', form=form)


@user_api.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):

                response = make_response(redirect(url_for('user_api.index')))
                access_token = generate_jwt_access_token(user)
                set_access_cookies(response, access_token)
                flash('You have been logged in!', 'success')
                
                return response

            flash('Login Unsuccessful. Please check your password', 'danger')

        flash('User does not exist. Please register.', 'danger')

    return render_template('login.html', form=form)


@user_api.route("/logout", methods=['GET', 'POST'])
def logout():
    response = make_response(redirect(url_for('user_api.index')))
    unset_jwt_cookies(response)
    flash('You have been logged out!', 'success')
    return response

@user_api.route("/forgot-password", methods=['GET', 'POST'])
def forgot_password():

    return redirect(url_for('user_api.index'))

@user_api.route("/change-password", methods=['GET', 'POST'])
def change_password():

    ##---##

    response = make_response(redirect(url_for('user_api.index')))
    unset_jwt_cookies(response)
    flash('Password changed successfully, please login again!', 'success')
    return response

@user_api.route('/blogs', methods=['GET'])
def blogs():
    blogs_all = Blogpost.query.order_by(desc('date_modified'))
    total_blogs = Blogpost.query.count()
    page_id = request.args.get('page')
    if not page_id:
        page_id = 1
    try:
        page_id = int(page_id)
        blogs = [blogs_all[i] for i in range(9*(page_id - 1), 9*page_id)]
    except ValueError:
        blogs = [blogs_all[i] for i in range(0, 9)]

    except IndexError:
        blogs = [blogs_all[i] for i in range(9*(page_id - 1), total_blogs)]

    return render_template('blogs.html', blogs=blogs)

@user_api.route('/blogs/<public_id>', methods=['GET'])
def blog_post(public_id):

    blogpost = Blogpost.query.filter_by(public_id=public_id).first()

    return render_template_string(source = blogpost.content, blog_post=blogpost)

@user_api.route('/editorials', methods=['GET'])
def editorials():
    editorials_all = Editorial.query.order_by(desc('date_modified'))
    total_editorials = Editorial.query.count()
    page_id = request.args.get('page')
    if not page_id:
        page_id = 1
    #try:
    page_id = int(page_id)
    editorials = [editorials_all[i] for i in range(9*(page_id - 1), total_editorials)]
    #editorials = [editorials_all[i] for i in range(9*(page_id - 1), 9*page_id)]
    #except ValueError:
    #    editorials = [editorials_all[i] for i in range(0, 9)]

    #except IndexError:
    #    editorials = [editorials_all[i] for i in range(9*(page_id - 1), total_editorials)]

    return render_template('editorials.html', editorial_post=editorials)

@user_api.route('/editorials/<public_id>', methods=['GET'])
def editorial_post(public_id):

    editorial_post = Editorial.query.filter_by(public_id=public_id).first()
    toc_string = editorial_post.toc
    toc_list = toc_string.split(',')
    toc = [sections.split('--') for sections in toc_list]
    toc_string_lower = toc_string.lower()
    toc_string_lower_updated = toc_string_lower.replace('--', ',')
    toc_string_lower_updated1 = toc_string_lower_updated.replace(' ', '-')
    toc_id_list = toc_string_lower_updated1.split(',')

    return render_template_string(source = editorial_post.content, editorial_post=editorial_post, toc = toc, toc_id = toc_id_list)

@user_api.route('/podcasts', methods=['GET'])
def podcasts():
    return render_template('podcasts.html')

@user_api.route('/contact', methods=['GET'])
def contact():
    return render_template('contact.html')

@user_api.route('/profile-edit', methods=['GET', 'POST', 'PUT'])
@jwt_required()
def profile_edit():
    form = ProfileEditForm()
    claims = get_jwt()

    if form.validate_on_submit():
        user = User.query.filter_by(public_id=claims['public_id']).first()
        user.name = form.name.data
        user.bio = form.bio.data
        user.linkedin = form.linkedin.data
        user.facebook = form.facebook.data
        user.twitter = form.twitter.data
        user.instagram = form.instagram.data
        
        if form.email.data != user.email:
            user.email = form.email.data
            user.email_verified = False
        
        db.session.commit()

        user = User.query.filter_by(public_id=claims['public_id']).first()
        
        access_token = generate_jwt_access_token(user)
        
        response = make_response(redirect(url_for('user_api.index')))
        set_access_cookies(response, access_token)
        flash('Profile updated successfully', 'success')
        return response


    return render_template('editprofile.html', profile=claims)

@user_api.route('/user/<name>', methods=['GET'])
def profile(name):
    name_with_spaces = name.replace("-", " ")
    profile = User.query.filter_by(name=name_with_spaces)
    return render_template('profile.html', profile = profile)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta property="og:image" content="assets/img/thebaton_logo_twitter.png">
    <meta name="twitter:image" content="assets/img/thebaton_logo_twitter.png">
    {% if title %}
    <meta name="twitter:title" content="TheBaton - {{ title }}">
    {% elif page_name %}
    <meta name="twitter:title" content="TheBaton - {{ page_name }}">
    {% else %}
    <meta name="twitter:title" content="TheBaton">
    {% endif %}

    {% if sub_title %}
        <meta name="twitter:description" content="{{ sub_title }}">
        <meta name="description" content="{{ sub_title }}">
    {% elif page_name %}
        <meta name="twitter:description" content="TheBaton - {{ page_name }}">
        <meta name="description" content="TheBaton - {{ page_name }}">
    {% else %}
        <meta name="twitter:description" content="TheBaton">
        <meta name="description" content="TheBaton">
    {% endif %}
    <meta name="twitter:card" content="summary_large_image">
    <meta property="og:type" content="website">

    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='logo-fav/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='logo-fav/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='logo-fav/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='logo-fav/site.webmanifest') }}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    
    {% block title %}
    {% endblock %}


</head>
<body>
        <!-- Start: Navigation Clean -->
        <nav class="navbar navbar-light navbar-expand-md navigation-clean">
            <div class="container"><a class="navbar-brand" href="{{ url_for('user_api.index') }}"><img src="{{ url_for('static', filename='logo-fav/thebaton_logo_1000x160.png') }}" alt="TheBaton Logo"></a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navcol-1">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item"><a class="nav-link active" href="{{ url_for('user_api.index') }}">Home</a></li>
                        <li class="nav-item"><a class="nav-link active" href="{{ url_for('user_api.blogs') }}">Blogs</a></li>
                        <li class="nav-item"><a class="nav-link active" href="{{ url_for('user_api.editorials') }}">Editorials</a></li>
                        <li class="nav-item"><a class="nav-link active" href="{{ url_for('user_api.podcasts') }}">Podcasts</a></li>
                        <li class="nav-item"><a class="nav-link active" href="{{ url_for('user_api.contact') }}" >Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav><!-- End: Navigation Clean -->
    <div class="hero-body">
        <div class="has-text-centered">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                        {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block content %}
            {% endblock %}

        </div>
    </div>

    <!-- Start: Footer Dark -->
    <footer class="footer-dark">
        <div class="container">
            <div class="row">
                <!-- Start: Services -->
                <div class="col-sm-6 col-md-3 item">
                    <h3>Pages</h3>
                    <ul>
                        <li><a href="{{ url_for('user_api.index') }}">Home</a></li>
                        <li><a href="{{ url_for('user_api.blogs') }}">Blogs</a></li>
                        <li><a href="{{ url_for('user_api.editorials') }}">Editorials</a></li>
                        <li><a href="{{ url_for('user_api.podcasts') }}">Podcasts</a></li>
                        <li><a href="{{ url_for('user_api.contact') }}">Contact</a></li>
                    </ul>
                </div><!-- End: Services -->
                <!-- Start: About -->
                <div class="col-sm-6 col-md-3 item">
                    <h3>User Management</h3>
                    <ul>
                        <li><a href="{{ url_for('user_api.register') }}">Register</a></li>
                        <li><a href="{{ url_for('user_api.login') }}">Login</a></li>
                        <li><a href="{{ url_for('user_api.logout') }}">Logout</a></li>
                    </ul>
                </div><!-- End: About -->
                <!-- Start: Footer Text -->
                <div class="col-md-6 item text">
                    <h3>TheBaton</h3>
                    <p>TheBaton provides an open-ended, peer-reviewed forum for scholarly discussions of legal and socio-political issues of importance. We seek to promote conscientious and honest dialogue on issues affecting the global population through publishing pieces written by students and practitioners.</p>
                </div><!-- End: Footer Text -->
                <!-- Start: Social Icons -->
                <div class="col item social">
                    <a href="https://www.facebook.com/thebatonofficial" target="_blank"><i class="icon ion-social-facebook"></i></a>
                    <a href="https://www.linkedin.com/company/thebatonofficial" target="_blank"><i class="icon ion-social-linkedin"></i></a>
                    <a href="https://twitter.com/thebatonindia" target="_blank"><i class="icon ion-social-twitter"></i></a>
                    <a href="https://www.instagram.com/thebatonofficial" target="_blank"><i class="icon ion-social-instagram"></i></a>
                </div><!-- End: Social Icons -->
            </div><!-- Start: Copyright -->
            <p class="copyright">TheBaton © 2021</p><!-- End: Copyright -->
        </div>
    </footer><!-- End: Footer Dark -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='js/vanilla-tilt.js') }}"></script>    

</body>
</html>

src/templates/blogpost.html
{% extends "base.html" %}


{% block title %}
<title>TheBaton - {{ blog_post.title }}</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/blogpost.css') }}">
{% set title = blog_post.title %}
{% set sub_title = blog_post.sub_title %}

{% endblock %}
{% block content %}
<header class="masthead" style="background-image:linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url('{{ blog_post.cover_image }}');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-8 mx-auto">
                <div class="post-heading">
                    <h1><strong>{{ blog_post.title }}</strong></h1>
                    <h2 class="subheading">{{ blog_post.sub_title }}</h2><span class="meta">Posted by&nbsp;<a href="#">{{ blog_post.author.name }}</a>&nbsp;on {{ blog_post.date_posted.strftime('%d %B %Y') }}</span>
                </div>
            </div>
        </div>
    </div>
</header>

<article>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-8 mx-auto" style="font-family: Montserrat, sans-serif;text-align: justify;">
                {% block blogpost %}
                {% endblock blogpost %}
            </div>
        </div>
    </div>
</article>

{% endblock content%}

src/templates/blogs.html
{% extends "base.html" %}


{% block title %}
<title>TheBaton - Blogs</title>
<link rel="stylesheet" href="static/css/blogs.css">
{% set page_name = "Blogs" %}

{% endblock %}


{% block content %}

<header class="art">
    <section class="art-text">
        <h1>RECENT BLOGS</h1>
        <!-- <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor.</h2> -->
    </section>
    <section class="art-grid">
        {% for blog in blogs %}
        <article class="art-element" data-tilt>
            <a href="/blogs/{{ blog.public_id }}">
            <img src="{{ blog.cover_image }}" alt="blog thumbnail">
            <div class="container">
                <h3>{{ blog.title }}</h3>
                <p>{{ blog.cta_title }}</p>
            </div>
            </a>
        </article>
        {% endfor %}
    </section>
    <section class="art-btn">
        
        {% set current_page_id = req_args.get('page') %}
        
        {% if not current_page_id %}
            {% set page_id = 2 %}
        {% else %}
            {% set page_id = int(current_page_id) + 1 %}
        {% endif %}

        <button><a href="/blog?page={{ page_id }}"> READ MORE</a></button>
    </section>
</header>
{% endblock %}

src/templates/contact.html
{% extends "base.html" %}


{% block title %}
<title>TheBaton - Contact</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/Highlight-Blue.css') }}">

{% endblock %}


{% block content %}
<section class="highlight-blue">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">Coming Soon</h2>
            <p class="text-center">Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh erat, pellentesque ut laoreet vitae. </p>
        </div>
        <div class="buttons"><a class="btn btn-primary" role="button" href="#">Home</a></div>
    </div>
</section>
{% endblock %}

src/templates/editorialpost.html
{% extends "base.html" %}


{% block title %}
<title>TheBaton - {{ editorial_post.title }}</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/editorialpost.css') }}">
{% set title = editorial_post.title %}
{% set sub_title = editorial_post.sub_title %}

{% endblock %}

{% block content %}

<section class="article-dual-column" style="font-family: Montserrat, sans-serif;">
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <div class="intro">
                    <h1 class="text-center"><strong>{{ editorial_post.title }}</strong><br></h1>
                    <h4 class="text-center" style="font-size: 19px;"><em>{{ editorial_post.sub_title }}</em><br></h4>
                    <p class="text-center"><span class="by">by</span> <a href="#">{{ editorial_post.author.name }}</a><span class="date">{{ editorial_post.date_posted.strftime('%d %B %Y') }} </span></p>
                    <div class="text-center"><img class="img-fluid" src="{{ editorial_post.cover_image }}"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-lg-3 offset-md-1">
                <div class="toc">
                    <p>Table of Contents</p>
                    <ul>
                    {% for items in toc %}
                        
                        <li>{{ items[0] }}</li>
                        {% if len(items) > 1 %}
                            {% for i in range(1, len(items)) %}
                            <ul><li>{{ items[i] }}</li></ul>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                    </ul>
                </div>
                {% if editorial_post.keywords %}
                <div class="toc">
                    <p>Keywords</p><span><em>{{ editorial_post.keywords }}</em></span>
                </div>
                {% endif %}
            </div>
            <div class="col-md-10 col-lg-7 offset-md-1 offset-lg-0">
                <div class="text">
                    {% block editorialpost %}
                    {% endblock editorialpost %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

src/templates/editorials.html
{% extends "base.html" %}


{% block title %}
<title>TheBaton - Editorials</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/editorials.css') }}">
{% set page_name = "Editorials" %}


{% endblock %}


{% block content %}

<header class="art">
    <section class="art-text">
        <h1>FEATURED EDITORIALS</h1>
        <!-- <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor.</h2> -->
    </section>
    <section class="art-grid">
        {% for editorial in editorial_post %}
        <article class="art-element" data-tilt>
            <a href="/editorials/{{ editorial.public_id }}">
            <img src='{{ editorial.cover_image }}' alt="editorial thumbnail">
            <div class="container">
                <h3>{{ editorial.title }}</h3>
                <p>{{ editorial.cta_title }}</p>
            </div>
            </a>
        </article>
        {% endfor %}
    </section>
    <section class="art-btn">
        
        {% set current_page_id = req_args.get('page') %}
        
        {% if not current_page_id %}
            {% set page_id = 2 %}
        {% else %}
            {% set page_id = int(current_page_id) + 1 %}
        {% endif %}

        <button><a href="/editorials?page={{ page_id }}"> NEXT PAGE</a></button>
    </section>
</header>
{% endblock %}

src/templates/editprofile.html
{% extends "base.html" %}


{% block title %}
<title>TheBaton - Edit Profile</title>
<link rel="stylesheet" href="static/css/editprofile.css">

{% endblock %}

{% block content %}
<section class="contact-clean">
    <form method="post">
        <h2 class="text-center">Edit Profile</h2><label>Label</label>
        <div>
            <div class="form-group"><input class="form-control" type="text" placeholder="Full Name" value="{% if profile.name %}{{ profile.name }}{% endif %}"></div>
            <div class="form-group"><input class="form-control" type="text" placeholder="Email" value="{% if profile.email %}{{ profile.email }}{% endif %}"></div>
            <div class="form-group"><input class="form-control" type="text" placeholder="Bio" value="{% if profile.bio %}{{ profile.bio }}{% endif %}"></div>
        </div><label>Socials</label>
        <div>
            <div class="form-group"><input class="form-control" type="text" placeholder="LinkedIn" value="{% if profile.linkedin %}{{ profile.linkedin }}{% endif %}"></div>
            <div class="form-group"><input class="form-control" type="text" placeholder="Instagram" value="{% if profile.instagram %}{{ profile.instagram }}{% endif %}"></div>
            <div class="form-group"><input class="form-control" type="text" placeholder="Facebook" value="{% if profile.facebook %}{{ profile.facebook }}{% endif %}"></div>
            <div class="form-group"><input class="form-control" type="text" placeholder="Twitter" value="{% if profile.twitter %}{{ profile.twitter }}{% endif %}"></div>
        </div><label>Change Password</label>
        <div>
            <div class="form-group"><input class="form-control" type="text" placeholder="Current Password"></div>
            <div class="form-group"><input class="form-control" type="text" placeholder="New Password"></div>
            <div class="form-group"><input class="form-control" type="text" placeholder="Confirm Password"></div>
        </div>
        <div class="form-group"><button class="btn btn-primary" type="submit">send </button></div>
    </form>
</section>
{% endblock %}

src/templates/login.html
{% extends "base.html" %}


{% block title %}
<title>TheBaton - Login</title>
<link rel="stylesheet" href="static/css/login.css">

{% endblock %}
{% block content %}

<!-- Start: Registration Form with Photo -->
<section class="register-photo">
    <!-- Start: Form Container -->
    <div class="form-container">
        <!-- Start: Image -->
        <div class="image-holder"></div><!-- End: Image -->
        <form method="post" action="">

            {{ form.hidden_tag() }}
            <h2 class="text-center"><strong>Login</strong></h2>
            <div class="form-group">
                {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg", placeholder="Email") }}
                {% endif %}
            </div>
            <div class="form-group">
                {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg", placeholder="Password") }}
                {% endif %}
            </div>
            <div class="form-group">
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </div>
            <div class="form-group">
                <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Log In</button>
            </div>
        
            <a class="forgot" href="{{ url_for('user_api.forgot_password') }}">Forgot Password?</a>
            <a class="already" href="{{ url_for('user_api.register') }}">Need an account? Register here</a>
        </form>
    </div><!-- End: Form Container -->
</section><!-- End: Registration Form with Photo -->

{% endblock %}

src/templates/register.html
{% extends "base.html" %}


{% block title %}
<title>TheBaton - Sign Up</title>
<link rel="stylesheet" href="static/css/register.css">

{% endblock %}
{% block content %}

<!-- Start: Registration Form with Photo -->
<section class="register-photo">
    <!-- Start: Form Container -->
    <div class="form-container">
        <!-- Start: Image -->
        <div class="image-holder"></div><!-- End: Image -->
        <form method="post" action="">

            {{ form.hidden_tag() }}
            <h2 class="text-center"><strong>Create</strong> an account.</h2>
            <div class="form-group">
                {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg", placeholder="Full Name") }}
                {% endif %}
            </div>
            <div class="form-group">
                {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg", placeholder="Email") }}
                {% endif %}
            </div>
            <div class="form-group">
                {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg", placeholder="Password") }}
                {% endif %}
            </div>
            <div class="form-group">
                {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg", placeholder="Confirm Password") }}
                {% endif %}
            </div>


            <div class="form-group">
                <div class="form-check"><label class="form-check-label"><input class="form-check-input" type="checkbox" required>I agree to the license terms.</label></div>
            </div>
            <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Sign Up</button>
            </div><a class="already" href="{{ url_for('user_api.login') }}">You already have an account? Login here.</a>
        </form>
    </div><!-- End: Form Container -->
</section><!-- End: Registration Form with Photo -->

{% endblock %}